Started
[{ Universe(s): 3, Sync_Universe: 4, Values: [1, 2, 4, 8, 16, 32, 64, 128, 128, 64, 32, 16, 8, 4, 2, 1, 0] }, { Universe(s): 4, Sync_Universe: 4, Values: [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 55, 34, 21, 13, 8, 5, 3, 2, 1, 1] }, ]
Error Encountered: Io(Custom { kind: WouldBlock, error: "No data available in given timeout" })
Name: 1, Universes: [1, 2, 3, 4]
